name = "ExternalDocstrings"
uuid = "e189563c-0753-4f5e-ad5c-be4293c83fb4"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.2-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestFunctionRunner = "792026f5-ac9a-4a19-adcb-47b0ce2deb5d"

[targets]
test = ["Test", "TestFunctionRunner"]
